name = "SavitskyGolayFilters"
uuid = "f52a7a4e-f3c4-4810-b429-372b32c00cf9"
authors = ["Hugo Levy-Falk"]
version = "0.1.0"

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"

[compat]
DSP = "0.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
